


services:
  postgres:
    image: postgres:15.15-alpine
    ports:
      - "5432:5432"
    # volumes:
      # - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=skim


# volumes:
#   postgres_data: